name: extructura_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'
  

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  
  cached_network_image: ^3.2.0
  camera: ^0.10.0+1
  cupertino_icons: ^1.0.2
  dio_http_cache: ^0.3.0
  dio: ^4.0.0
  exif: ^3.0.0
  file_picker: ^5.0.1
  flutter_image_compress: ^1.1.0
  flutter_tesseract_ocr: ^0.4.20
  image_cropper: ^3.0.0
  image_picker: ^0.8.3+3
  image: ^3.1.3
  indexed_list_view: ^2.0.2
  intl: ^0.17.0
  mvc_pattern: ^8.8.2
  path_provider: ^2.0.9
  path: ^1.8.0
  pdfx: ^2.2.0
  permission_handler: ^10.0.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  

dev_dependencies:
  flutter_lints: ^2.0.1
  change_app_package_name: ^1.1.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/tessdata/
    - i18n/es.json
    - i18n/en.json
    - images/
    - lib/settings/app_settings.json
  fonts:
    - family: Sans 
      fonts:
        - asset: fonts/DMSans-Bold.ttf
          weight: 700
        - asset: fonts/DMSans-Medium.ttf
          weight: 500
        - asset: fonts/DMSans-Regular.ttf
