name: extructura_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'
  

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  
  cached_network_image: ^3.2.0
  camera: ^0.10.0+1
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  device_info_plus: any
  dio_cache_interceptor: ^3.3.1
  dio: ^4.0.0
  exif: ^3.0.0
  file_picker: ^5.0.1
  flutter_image_compress: ^1.1.0
  flutter_tesseract_ocr: ^0.4.20
  image_cropper: ^3.0.0
  image_picker: ^0.8.3+3
  image: ^3.1.3
  indexed_list_view: ^2.0.2
  intl: ^0.18.0
  mvc_pattern: ^8.8.2
  path_provider: ^2.0.9
  path: ^1.8.0
  pdfx: ^2.3.0
  permission_handler: ^10.0.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  flutter_native_splash: any
  dropdown_button2: ^2.1.3
  open_file: ^3.3.2
  csv: ^5.0.2
  page_view_dot_indicator: ^1.1.0
  window_manager: ^0.2.7
  flutter_twain_scanner: ^0.1.0

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: fd519be1e8398c6b6c2062c2447bac960a71bc02

dev_dependencies:
  flutter_lints: ^2.0.1
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  # Global
  image_path: "images/app_icon/icon.png"
  # Android
  android: "launcher_icon"
  adaptive_icon_background: "#0D658B"
  adaptive_icon_foreground: "images/app_icon/icon_transparent_background.png"
  # Windows
  windows:
    generate: true
    image_path: "images/app_icon/icon.png"
    icon_size: 48

flutter_native_splash:
  color: "#0D658B"
  image: "images/app_icon/icon_transparent_background.png"
  android_12:
    image: images/app_icon/icon_transparent_background.png



flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/tessdata/
    - i18n/es.json
    - i18n/en.json
    - images/
    - images/app_icon/
    - images/tutorial/
    
  fonts:
    - family: Sans 
      fonts:
        - asset: fonts/DMSans-Bold.ttf
          weight: 700
        - asset: fonts/DMSans-Medium.ttf
          weight: 500
        - asset: fonts/DMSans-Regular.ttf
  
