# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.1'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

      - name: Upload to Slack
        uses: adrey/slack-file-upload-action@master
        with:
          token: xoxb-5311098642502-5317907329555-C5Yo6UUTYZ4q0w57J7iEFjG0
          path: build/app/outputs/flutter-apk/app-release.apk
          channel: canal-ejemplo
          filename: "Nuevo Nombre"
          initial_comment: 'Apk Generada!'
          title: "title"


      # - uses: MeilCli/slack-upload-file@v3
      #   with:
      #     slack_token:  xoxb-5311098642502-5317907329555-C5Yo6UUTYZ4q0w57J7iEFjG0
      #     channel_id: C059QBG2U9F
      #     file_path: build/app/outputs/flutter-apk/app-release.apk
      #     initial_comment: 'Apk Generada!'
     
      
      

      # - name: Post to a Slack channel
      #   uses: slackapi/slack-github-action@v1.24.0
      #   with:
      #     # Slack channel id, channel name, or user id to post message.
      #     # See also: https://api.slack.com/methods/chat.postMessage#channels
      #     # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
      #     channel-id: 'C059QBG2U9F' # ID del canal en donde se va a mandar el mensaje
      #     # For posting a simple plain text message
      #     slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
      #   env:
      #     SLACK_BOT_TOKEN: xoxb-5311098642502-5317907329555-C5Yo6UUTYZ4q0w57J7iEFjG0

      #