# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.1'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      # Uploads apk to github artifacts
      # - name: Upload APK
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: release-apk
      #     path: build/app/outputs/apk/release/app-release.apk
    
      - name: Copy-Rename APK
        uses: canastro/copy-file-action@master
        with:
          source: "build/app/outputs/flutter-apk/app-release.apk"
          target: "Extructura-APP-26-05-2023-v1.apk"

      - name: Upload APK to Slack
        uses: MeilCli/slack-upload-file@v3
        with:
          slack_token:  xoxb-5311098642502-5317907329555-C5Yo6UUTYZ4q0w57J7iEFjG0
          channel_id: C059QBG2U9F
          file_path: Extructura-APP-26-05-2023-v1.apk
          initial_comment: 'Apk Generada!'