name: Get Branch Name 

on:
  pull_request: 
    branches: [ "development" ]

jobs:
  set_head_branch_name:
    permissions: write-all
    runs-on: ubuntu-latest
    steps: 
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v7

      - name: Sanitize Branch Name
        id: sanitize-branch-name
        uses: frabert/replace-string-action@v2
        with:
          string: '${{ steps.branch-name.outputs.head_ref_branch }}'
          pattern: '(?:\.(?![^.]+$)|[^\w\d\n.])+'
          replace-with: '_'
      
      - name: Modify head_branch.txt
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          branch: "${{ steps.branch-name.outputs.head_ref_branch }}"
          path: head_branch.txt
          body: "${{ steps.sanitize-branch-name.outputs.replaced }}"
          overwrite: 'true'