name: Get Branch Name 

on:
  pull_request: 
    branches: [ "development" ]

jobs:
  set_head_branch_name:
    permissions: write-all
    runs-on: ubuntu-latest
    steps: 
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v7

      - name: Check PR title
        env:
          TITLE: ${{ steps.branch-name.outputs.head_ref_branch }}
        run: |
          echo "$TITLE"
      
      - name: Get Head Ref branch name (i.e The current pull request branch)
        run: |
          echo "$TITLE"
      
      - name: Modify head_branch.txt
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          branch: "${{ steps.branch-name.outputs.head_ref_branch }}"
          path: head_branch.txt
          body: "$TITLE"
          overwrite: 'true'

 